### ISSUE TITLE
[Feature] Option for the bot to disconnect once the chimes are done?

### ISSUE THREAD

**Issue by Ufinexa** [jamiesage123/big-ben-clock-discord-bot#6]
Would be amazing to have it disconnect once it has finished doing what it needs to and then rejoin when it is on the hour again

**Comment by jamiesage123** [comment]
Hey @Ufinexa 

That is the intended functionality but I believe it was slightly bugged due to recent discord updates.

I've merged in #5 and a couple of other commits that will hopefully sort this problem out.

The code is available in [master](https://github.com/jamiesage123/big-ben-clock-discord-bot/tree/master) and has also been [tagged](https://github.com/jamiesage123/big-ben-clock-discord-bot/releases/tag/v0.1.0)
